### PR TITLE
removes the "compile-time" config in favor of "provided"

### LINKED ISSUE #654: Unexpected inject of `scala3-library` by the `TypelevelKernelPlugin`
In the Open Community Build for typelevel/spotted-leopards I've seen a strange failures when building docs under 3.4.0-NIGHTLY. [Build logs](https://github.com/VirtusLab/community-build3/actions/runs/6593524845/job/17918003143). 
One of the reasons of failures were duplicated entries of `scala3-library`. The error message was as following
  
```scala
  object caps does not have a member type Cap while compiling ...
```
where `caps.Cap` is the experimental part of Caprese project (Capture Calculus) https://github.com/lampepfl/dotty/blob/15033c7ac8be33a1b94226da3cca3922b53066ce/library/src/scala/caps.scala#L7 

Why this symbol was required in building docs is out of the scope of this issue. What's important is the fact the for some reason `scala3-library:3.3.0` was present on the classpath when building docs insteead of expected nightly version of stdlib. After poking around I've found the following injected externalDependecies
```
show coreJVM/unmanagedClasspath
[info] * Attributed(/home/gitpod/.cache/coursier/v1/https/repo1.maven.org/maven2/org/typelevel/scalac-compat-annotation_3/0.1.2/scalac-compat-annotation_3-0.1.2.jar)
[info] * Attributed(/home/gitpod/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.3.0/scala3-library_3-3.3.0.jar)
[info] * Attributed(/home/gitpod/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.10/scala-library-2.13.10.jar)
```

Inspection of unmanaged classpath pointed me to this project: 
```scala
inspect coreJVM/unmanagedClasspath
...
[info]  ProjectRef(uri("file:/workspace/spotted-leopards/"), "coreJVM") / Compile / unmanagedClasspath
[info] Defined at:
[info]  (sbt.Classpaths.classpaths) Defaults.scala:2709
[info]  (org.typelevel.sbt.TypelevelKernelPlugin.projectSettings) TypelevelKernelPlugin.scala:62
```

The `scala3-library:3.3.0` seems to be injected in here in `TypeLevelKernelPlugin` https://github.com/typelevel/sbt-typelevel/blob/076d867b216b295ce501e29f54b19c5f75ac1329/kernel/src/main/scala/org/typelevel/sbt/TypelevelKernelPlugin.scala#L62

I don't know the purpose of this inject and if it really required. I only want to spot some light on it.
When it comes to failures in the scaladoc I think there might some some bug, because during normal compilation duplicate stdlib entries seems not to be the problems, altough I would try to reproduce it and report to the dotty repo.

### PR DESCRIPTION
**Pull request by satorg**
May resolve #654

### CODE REVIEW

File: kernel/src/main/scala/org/typelevel/sbt/TypelevelKernelPlugin.scala [hunk 1]
```diff
@@ -29,7 +29,8 @@ object TypelevelKernelPlugin extends AutoPlugin {
   override def trigger = allRequirements
 
   object autoImport {
-    lazy val CompileTime: Configuration = config("compile-time").hide
+    @deprecated("use `Provided` instead", "0.6.1")
+    lazy val CompileTime: Configuration = Provided
```
Comment (armanbilge) [inline kernel/src/main/scala/org/typelevel/sbt/TypelevelKernelPlugin.scala:33]: Since we're deprecating it anyway I wonder if we should leave the old definition. Also I wonder if anyone could have been using it like `"compile-time"` instead of `CompileTime`.

**Review by armanbilge — APPROVED** [review]
Thank you Sergey :)
